In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(np.sum(arr))

10


# Aggregate Function

In [3]:
# mean
np.mean(arr)

np.float64(2.5)

In [4]:
# modian
np.median(arr)

np.float64(2.5)

In [6]:
# std
np.std(arr)

np.float64(1.118033988749895)

In [11]:
# varience
np.var(arr)

np.float64(1.25)

In [12]:
# mini
np.min(arr)

np.int64(1)

In [13]:
np.max(arr)

np.int64(4)

In [19]:
arr = np.array([[1,2,3,4],
                 [5,6,7,8]])
arr.ndim

2

In [26]:
print(np.sum(arr, axis = 1))

[10 26]


In [25]:
print(np.sum(arr, axis = 0))

[ 6  8 10 12]


# Cumulative Opreation


In [29]:
arr1 = np.array([1,4,8])

In [30]:
print(np.cumsum(arr1)) # 1+4+8

[ 1  5 13]


In [31]:
print(np.cumprod(arr1)) # 1x4x8

[ 1  4 32]


# Conditional base choices

In [33]:
# where 
result  = np.where(arr1 <2, 'low', 'high' )
result

array(['low', 'high', 'high'], dtype='<U4')

In [36]:
arr = np.array([10,30,50,35,76])
print(np.argwhere(arr > 20)) # it give u the index if the condition is True

[[1]
 [2]
 [3]
 [4]]


In [38]:
arr = np.array([[1,2,3,4],
                 [5,6,7,8]])

In [41]:
arr2 = np.argwhere(arr>3)
arr2

array([[0, 3],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3]])

In [56]:
# Logical and
mask  = np.logical_and(arr>3, arr< 7)
print(arr[mask])
print(mask)

[4 5 6]
[[False False False  True]
 [ True  True False False]]


In [58]:
# Logical or
mask1  = np.logical_or(arr>3, arr>7)
print(arr[mask1])
print(mask1)

[4 5 6 7 8]
[[False False False  True]
 [ True  True  True  True]]


In [61]:
# non-zero
arr = np.array([1,0,4,0,8])
print(np.nonzero(arr))

(array([0, 2, 4]),)


In [ ]:
#