In [5]:
import numpy as np

# Broadcosting 

In [8]:
image = np.array([[1,2,3],[5,6,7,]])
print(image)
image.shape

[[1 2 3]
 [5 6 7]]


(2, 3)

In [10]:
brigtness = image + 2
brigtness
brigtness.shape

(2, 3)

In [15]:
arr = np.array([[1,2,3],
                
                [7,8,9]])
arr.shape

(2, 3)

In [14]:
arr1 = np.array([10,30,40])
arr1.shape

(3,)

In [18]:
arr2 = arr + arr1
arr2

array([[11, 32, 43],
       [17, 38, 49]])

In [20]:
arr3 = np.array([[1,2,3],
                
                [7,8,9]])
arr3.shape

(2, 3)

In [23]:
arr4 = np.array([10])
arr4.shape

(1,)

In [24]:
arr5 = arr3 + arr4
arr5

array([[11, 12, 13],
       [17, 18, 19]])

# Vectorization

In [26]:
def square(x):
    return x*x

vfunc = np.vectorize(square)



In [28]:
arr = np.array([1,2,3,5])

In [29]:
print(vfunc(arr))

[ 1  4  9 25]


In [35]:
# Dealing with massing values
arr = np.array([1,2,4, np.nan, 3]) # add nan value
arr

array([1. , 2. , 4. , nan, 3.3])

In [32]:
print(np.isnan(arr))

[False False False  True False]


In [36]:
arr = np.array([1,2,3, np.inf, np.nan]) # add infinit value

In [37]:
print(np.isinf(arr))

[False False False  True False]


In [44]:
print(np.logical_or(np.isinf(arr), np.isnan(arr)))


[False False False  True  True]


In [46]:
new_arr = np.nan_to_num(arr) # remove NAN and infinite values
new_arr

array([1.00000000e+000, 2.00000000e+000, 3.00000000e+000, 1.79769313e+308,
       0.00000000e+000])