# Ceating Numpy Array

In [3]:
import numpy as np

# 1️⃣ Basic Array
arr = np.array([1, 2, 3, 4, 5])
print("Basic Array:", arr)


Basic Array: [1 2 3 4 5]


In [4]:
# 2️⃣ 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [5]:
# 3️⃣ Zeros Array
zeros_arr = np.zeros((2, 3))
print("Zeros Array:\n", zeros_arr)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 4️⃣ Ones Array
ones_arr = np.ones((3, 4))
print("Ones Array:\n", ones_arr)


Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# 5️⃣ Identity Matrix
eye_arr = np.eye(3)
print("Identity Matrix:\n", eye_arr)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# 6️⃣ Range Array (arange)
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)


Range Array: [0 2 4 6 8]


In [9]:
# 7️⃣ linspace
lin_arr = np.linspace(0, 1, 5)
print("Linspace Array:", lin_arr)


Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [10]:
# 8️⃣ logspace
log_arr = np.logspace(1, 3, 3)
print("Logspace Array:", log_arr)


Logspace Array: [  10.  100. 1000.]


In [11]:
# 9️⃣ Random Array
rand_arr = np.random.rand(2, 2)
print("Random Array:\n", rand_arr)


Random Array:
 [[0.97982191 0.97493031]
 [0.9395683  0.19185109]]


In [12]:
# 🔟 Full Array
full_arr = np.full((2, 3), 7)
print("Full Array:\n", full_arr)


Full Array:
 [[7 7 7]
 [7 7 7]]


In [13]:
# 🔟 Full Array
full_arr = np.full((2, 3), 7)
print("Full Array:\n", full_arr)


Full Array:
 [[7 7 7]
 [7 7 7]]


In [14]:
# 1️⃣1️⃣ Empty Array
empty_arr = np.empty((2, 3))
print("Empty Array:\n", empty_arr)


Empty Array:
 [[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]
