# Indexing And Slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50, 60, 70 ,80, 90 ])
print(arr[:9])

[10 20 30 40 50 60 70 80 90]


In [3]:
# Positive Indexing
print(arr[0:3])

[10 20 30]


In [5]:
# Negative Indexing
print(arr[-1:-6:-1])

[90 80 70 60 50]


In [6]:
# Step Indexing
print(arr[::2])

[10 30 50 70 90]


In [19]:
matrix =np.array ([[1,2,3],
                  [4,5,7],
                  [8,9,0]
])

print(matrix[0:3, 0:1])
# matrix.ndim

[[1]
 [4]
 [8]]


In [18]:
print(matrix[1:, 0:2])

[[4 5]
 [8 9]]


In [25]:
print(matrix[-1:, -1:])

[[0]]


In [27]:
print(matrix[0:1,0:1])

[[1]]


# np.take functin


In [29]:
arr = np.array([10, 20, 30, 40, 50, 60, 70 ,80, 90 ])
ind = [0,-1]
print(np.take(arr, ind))

[10 90]


In [30]:
ind = [1,3,-2]
print(np.take(arr, ind))

[20 40 80]


# np.nditer using for looping array

In [37]:
arr = np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr):
    print(i, end=' ')

1 2 3 4 5 6 

# np.ndenumerate --> show index and value

In [40]:
for ind, x in np.ndenumerate(arr):
    print(ind, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# View and Copy

In [51]:
array = np.array([1,2,3,4,5])
view = array[1:3]
view[0]=200
print(view)
print(array) # array is changed

[200   3]
[  1 200   3   4   5]


In [53]:
array = np.array([1,2,3,4,5,6])
copy = array[1:3].copy()
copy[1]=200
print(copy)
print(array) # array is not change

[  2 200]
[1 2 3 4 5 6]
