In [3]:
import numpy as np

# -------------------------------
# Random numbers examples
# -------------------------------

# Random floats between 0 and 1 (1D array with 5 elements)
arr1 = np.random.random(5)
print("Random floats (0-1):", arr1)

# Random integers between 1 and 10, size = 5
arr2 = np.random.randint(1, 10, size=5)
print("Random integers (1-10):", arr2)

# Random numbers from normal distribution (3 rows, 2 columns)
arr3 = np.random.randn(3, 2)
print("Random normal distribution array (3x2):")
print(arr3)

print()  # Empty line for readability

# -------------------------------
# Shape example
# -------------------------------

# 2D array
arr4 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr4)
print("Shape of arr4:", arr4.shape)

print()  # Empty line

# Reshape example
arr5 = arr4.reshape(3, 2)
print("Reshaped Array (3x2):")
print(arr5)
print("Shape of arr5:", arr5.shape)

print()  # Empty line

# -------------------------------
# Dimension examples
# -------------------------------

# 1D array
arr6 = np.array([1, 2, 3])
print("1D Array:", arr6)
print("Dimension:", arr6.ndim)

# 2D array
arr7 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("2D Array:")
print(arr7)
print("Dimension:", arr7.ndim)

# 3D array
arr8 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print("3D Array:")
print(arr8)
print("Dimension:", arr8.ndim)


Random floats (0-1): [0.62773174 0.58497072 0.03928844 0.48128967 0.36557126]
Random integers (1-10): [6 4 3 2 8]
Random normal distribution array (3x2):
[[-3.01319628  0.34244667]
 [-2.20961866  0.47169186]
 [-0.22200197  0.25098551]]

2D Array:
[[1 2 3]
 [4 5 6]]
Shape of arr4: (2, 3)

Reshaped Array (3x2):
[[1 2]
 [3 4]
 [5 6]]
Shape of arr5: (3, 2)

1D Array: [1 2 3]
Dimension: 1
2D Array:
[[1 2 3]
 [4 5 6]]
Dimension: 2
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension: 3
