In [3]:
import numpy as np

In [6]:
# Transpose of a matrix

arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [7]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [32]:
#Swapaxes
arr = np.array([[1,2,3],[4,5,6]])
print('Normal array')
print(arr)

swapped = np.swapaxes(arr, 0, 1)
print('Swapped array')
print(swapped)

Normal array
[[1 2 3]
 [4 5 6]]
Swapped array
[[1 4]
 [2 5]
 [3 6]]


In [9]:
# Concatenation
a = np.array([1,2,3])
b = np.array([4,5,6])

combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4, 5, 6])

In [14]:
# vstack method
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.vstack((arr1, arr2))
result

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# hstack method
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.hstack((arr1, arr2))
result

array([1, 2, 3, 4, 5, 6])

In [38]:
# split 
arr = np.array([[1,2,3,4],
                [6,7,8,9]])
print(np.split(arr,1))

[array([[1, 2, 3, 4],
       [6, 7, 8, 9]])]


In [41]:
# vsplit 
arr = np.array([[1,2,3,4],
                [6,7,8,9]])
print(np.vsplit(arr,2))

[array([[1, 2, 3, 4]]), array([[6, 7, 8, 9]])]


In [46]:
# hsplit 
arr = np.array([[1,2,3,4],
                [6,7,8,9]])
print(np.hsplit(arr,4))

[array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]]), array([[4],
       [9]])]


In [47]:
# repating
arr = np.array([1,2,3,4])
print(np.repeat(arr,2))

[1 1 2 2 3 3 4 4]


In [49]:
# tile -> repate my whole array
arr = np.array([1,2,3,4])
print(np.tile(arr,4))

[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]
